### PR TITLE
Merge master to iris

### PR DESCRIPTION
**Pull request by cytadela8**

### CODE REVIEW

**Comment by gorbak25** [comment]
@velzevur @uwiger Is it time for the backmerge?

**Review by gorbak25 — APPROVED** [review]

**Comment by cytadela8** [comment]
Personally I'm more in favour of rebase. `iris` branch contains nearly nothing

**Comment by cytadela8** [comment]
I'm also investigating if something needs to be moved to aesophia as two of the changes files where moved there.

**Comment by cytadela8** [comment]
Nothing needs to be moved to aesophia. I think we should rebase the changes and consider merging to master.

**Comment by hanssv** [comment]
Some redundant things on `iris` branch - #485  will be cleaner I think?!

**Comment by cytadela8** [comment]
Replaced with #485

**Pull request closed without merging**
